name: playground
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: tensor-programming <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
